all:
	make -C ./SMSutils
	make -C ./collector
	make -C ./hook_module

fclean:
	make fclean -C ./SMSutils
	make fclean -C ./collector
	make fclean -C ./hook_module
clean:
	make clean -C ./SMSutils
	make clean -C ./collector
	make clean -C ./hook_module
re:
	make re -C ./SMSutils
	make re -C ./collector
	make re -C ./hook_module